export type AlertSeverity = 'critical' | 'high' | 'medium' | 'info'
export type AlertDepartment = 'operations' | 'procurement' | 'fleet' | 'finance' | 'hr' | 'safety'
export type AlertStatus = 'new' | 'acknowledged' | 'resolved'

export interface Alert {
  id: string
  severity: AlertSeverity
  title: string
  description: string
  department: AlertDepartment
  affectedEntity: string
  projectId: string
  timestamp: string
  status: AlertStatus
  acknowledgedBy?: string
  prescriptiveId?: string
  evidenceBullets: string[]
  predictedImpact?: string
}

export const alerts: Alert[] = [
  {
    id: 'ALT-001',
    severity: 'critical',
    title: 'Steel Supply Stockout Risk — 4 Days',
    description: 'TMT Steel Bars (Fe-500D) for Hyderabad Metro Pkg-3 at critically low stock level (42 MT vs 80 MT reorder point). PO-2847 from JSW Steel is 6 days delayed. At current consumption rate, site will hit zero stock in 4 days, halting viaduct casting operations.',
    department: 'procurement',
    affectedEntity: 'PO-2847 · JSW Steel Ltd',
    projectId: 'HYD-M3',
    timestamp: '2025-06-26T07:15:00',
    status: 'new',
    prescriptiveId: 'REC-001',
    evidenceBullets: [
      'Current stock: 42 MT | Reorder point: 80 MT | Daily consumption: ~10 MT',
      'PO-2847 (200 MT, ₹50.5L) expected June 20, now delayed by 6 days with no updated ETA from JSW',
      'Viaduct casting crew (38 persons) will be idle if material is unavailable — ₹2.8L daily labor cost at risk',
      'Adjacent project NH-44X has 185 MT surplus TMT — potential inter-project transfer possible',
    ],
    predictedImpact: 'Work stoppage in 4 days. Estimated ₹11L cost impact per week of delay.',
  },
  {
    id: 'ALT-002',
    severity: 'critical',
    title: 'Hydraulic Pump Failure — Volvo EC300E Grounded',
    description: 'VLV-EC300-002 (Volvo EC300E Excavator, HYD-M3) has been grounded since 16:45 yesterday with confirmed hydraulic pump failure. Machine is on the critical path for pile cap construction. Predictive model flagged this component 15 days ago with a high-risk alert that was not actioned.',
    department: 'fleet',
    affectedEntity: 'VLV-EC300-002 · HYD-M3',
    projectId: 'HYD-M3',
    timestamp: '2025-06-26T06:30:00',
    status: 'acknowledged',
    acknowledgedBy: 'Ravi Kumar',
    prescriptiveId: 'REC-002',
    evidenceBullets: [
      'Machine down since 16:45 June 25. Engine hours: 6,102. Pump life typically 5,500–6,000 hrs',
      'Predictive model (Volvo Connect) flagged hydraulic pump anomaly on June 11 — alert actioned 15 days late',
      'Replacement pump available: JSW Tools (Hyderabad) has stock. Delivery estimate: 36–48 hrs',
      'Critical path impact: pile cap casting for Station-7 cannot proceed without this machine',
    ],
    predictedImpact: '₹18.2K idle cost per day + ₹4.2L critical path delay per day.',
  },
  {
    id: 'ALT-003',
    severity: 'critical',
    title: 'Kaleshwaram Cost Overrun Approaching 10% Threshold',
    description: 'KDSP-B1 has recorded 8.6% cost overrun (₹42.3L actual vs ₹38.9L budget), driven by steel supply delays requiring emergency spot purchases at premium rates. Trajectory analysis predicts breach of 10% threshold — requiring board approval — within 18 days.',
    department: 'finance',
    affectedEntity: 'KDSP-B1 · Priya Menon',
    projectId: 'KDSP-B1',
    timestamp: '2025-06-25T23:00:00',
    status: 'new',
    prescriptiveId: 'REC-003',
    evidenceBullets: [
      'Current overrun: ₹33.6L (8.6%) — board threshold is 10% (₹38.9L)',
      'Root cause: 3 emergency steel purchases at +22% market premium due to PO delays',
      'Cement procurement also trending 4.2% above estimate due to local supply shortage',
      'If trajectory continues unchanged, threshold breach in 18 days (around July 14)',
    ],
    predictedImpact: 'Board notification required at 10% overrun. Project may face funding review.',
  },
  {
    id: 'ALT-004',
    severity: 'high',
    title: 'Hyderabad Metro Schedule Slip — 77 Days Behind',
    description: 'HYD-M3 is now 77 days behind the planned completion date of August 30, 2026. Two concurrent issues — crew productivity at 82% of plan and ongoing steel supply delays — are compounding. Updated CPM analysis forecasts November 15 completion.',
    department: 'operations',
    affectedEntity: 'HYD-M3 · Rajesh Nair',
    projectId: 'HYD-M3',
    timestamp: '2025-06-26T08:00:00',
    status: 'new',
    prescriptiveId: 'REC-004',
    evidenceBullets: [
      'Revised CPM completion: November 15, 2026 vs planned August 30, 2026 (77 days slip)',
      'Week-on-week schedule recovery less than 2 days — insufficient to close gap organically',
      'Viaduct casting crew productivity at 82% of plan (Week 23 productivity log)',
      'LD (Liquidated Damages) clause kicks in after 60-day delay — currently at 77 days',
    ],
    predictedImpact: 'LD exposure: ₹1.8L/day beyond 60-day delay. Current exposure: ₹30.6L.',
  },
  {
    id: 'ALT-005',
    severity: 'high',
    title: 'Screw Piles Delivery Delayed — Visakhapatnam Port',
    description: 'PO-2860 for marine grade screw piles (120 nos, ₹1.08Cr) from Atlas Copco India is 1 day overdue. Current stock of 45 nos has only 6 days remaining at current installation rate. Berth quay wall construction will stall without resolution.',
    department: 'procurement',
    affectedEntity: 'PO-2860 · Atlas Copco India',
    projectId: 'VIZG-P2',
    timestamp: '2025-06-26T07:45:00',
    status: 'new',
    prescriptiveId: 'REC-005',
    evidenceBullets: [
      'Stock: 45 nos | Consumption: 7-8 nos/day | Stockout: ~6 days',
      'PO-2860 overdue — Atlas Copco reports port congestion at Mundra delaying dispatch',
      'Alternative supplier identified: Keller Grundbau (Pune) — can dispatch in 4 days at +8% cost',
      'Site team has re-sequenced work to gain 2 additional buffer days',
    ],
    predictedImpact: 'Work stoppage risk in 6 days. Potential 2-week schedule impact.',
  },
  {
    id: 'ALT-006',
    severity: 'high',
    title: 'High Attrition Risk — 3 Key Staff on KDSP-B1',
    description: 'HR analytics has flagged 3 employees at KDSP-B1 (Kaleshwaram) with high attrition risk: Site Manager Priya Menon (sentiment declining), Civil Engineer Mohammed Shareef (productivity at 72%), and Store Keeper Shankar Gupta (attendance 86%). Remote site conditions are the primary driver.',
    department: 'hr',
    affectedEntity: 'KDSP-B1 · 3 employees',
    projectId: 'KDSP-B1',
    timestamp: '2025-06-25T18:00:00',
    status: 'new',
    prescriptiveId: 'REC-006',
    evidenceBullets: [
      'Site Manager (Priya Menon): engagement score declined 22pts in 6 weeks; workload index critical',
      'Civil Engineer (Mohammed Shareef): productivity at 72% of plan for 3 consecutive weeks',
      'Store Keeper (Shankar Gupta): attendance 86%, 3 unplanned absences in June',
      'KDSP-B1 is 180km from nearest city; accommodation and connectivity issues flagged in pulse survey',
    ],
    predictedImpact: 'Loss of Site Manager mid-project could add 6-8 weeks delay and ₹45L replacement cost.',
  },
  {
    id: 'ALT-007',
    severity: 'high',
    title: 'Railway Gauge Project PM Performance Below Threshold',
    description: 'Venkat Rao (PM, RLWY-G4) has recorded 74% productivity vs plan for 4 consecutive weeks. Schedule variance has grown to +15 days. Team engagement scores are the lowest in the portfolio. Retaining and supporting this PM is urgent.',
    department: 'hr',
    affectedEntity: 'RLWY-G4 · Venkat Rao',
    projectId: 'RLWY-G4',
    timestamp: '2025-06-25T16:00:00',
    status: 'acknowledged',
    acknowledgedBy: 'Kavitha Nair',
    evidenceBullets: [
      '4-week productivity average: 74% of plan (threshold: 80%)',
      'Team engagement score: 4.2/10 (org average: 6.8/10)',
      'PM attendance: 89% — 3 absences in June, not pre-approved',
      'Root cause likely: multi-agency coordination burden (CRS, Railway Board, civil contractor)',
    ],
    predictedImpact: 'Further schedule risk. If PM exits, cost to replace + knowledge transfer: ~₹80L impact.',
  },
  {
    id: 'ALT-008',
    severity: 'high',
    title: 'Komatsu HD785 Critical Bearing Failure — BMRC-E2',
    description: 'KMT-HD785-021 rear axle bearing failure confirmed. Machine grounded since June 25 22:10. KOMTRAX had flagged abnormal vibration patterns for 5 days prior. Replacement bearing ETA 3-4 days. The machine is a high-utilization dump truck central to spoil removal.',
    department: 'fleet',
    affectedEntity: 'KMT-HD785-021 · BMRC-E2',
    projectId: 'BMRC-E2',
    timestamp: '2025-06-25T22:30:00',
    status: 'acknowledged',
    acknowledgedBy: 'Ravi Kumar',
    evidenceBullets: [
      'Bearing failure confirmed by site mechanic. Machine grounded 22:10 June 25',
      'KOMTRAX vibration alert (5-day lead time) was not escalated through maintenance workflow',
      'Daily idle cost: ₹38,000. Replacement bearing cost: ₹1.4L (Komatsu authorized dealer)',
      'Spoil removal backlog building — 340 CUM uncleared at Station-4 excavation',
    ],
    predictedImpact: '₹38K/day idle cost + spoil removal backlog may delay next concrete pour by 3-4 days.',
  },
  {
    id: 'ALT-009',
    severity: 'medium',
    title: 'Bitumen VG-30 Approaching Reorder Point — NH-44X',
    description: 'Current stock of Bitumen VG-30 at NH-44X site is 35 MT against a reorder point of 50 MT. PO-2865 (200 MT) is pending approval. At current paving rate, stockout risk in 8 days.',
    department: 'procurement',
    affectedEntity: 'PO-2865 · HPCL Bulk Division',
    projectId: 'NH-44X',
    timestamp: '2025-06-26T06:00:00',
    status: 'new',
    evidenceBullets: [
      'Stock: 35 MT | Reorder: 50 MT | Paving consumption: 4-5 MT/day',
      'PO-2865 pending approval — requires Anand Sharma sign-off',
      'HPCL delivery lead time: 5-7 days from PO approval',
      'Expedite PO approval to prevent paving disruption',
    ],
    predictedImpact: 'If not approved today, 2-3 day paving stoppage risk next week.',
  },
  {
    id: 'ALT-010',
    severity: 'medium',
    title: 'Fleet Utilization Below Target — 4 Machines Idle',
    description: '4 machines across the portfolio are idle today with combined daily idle cost of ₹72,300. Key idle machines: Tata LPT 909G (KDSP-B1, 23% utilization), Eicher Pro 6025 (BMRC-E2, 31%), Volvo EC480D (VIZG-P2, 18%), KMT HD785 (breakdown). Demand re-allocation analysis is recommended.',
    department: 'fleet',
    affectedEntity: 'Portfolio · 4 Machines',
    projectId: 'HYD-M3',
    timestamp: '2025-06-26T08:45:00',
    status: 'new',
    evidenceBullets: [
      'Tata LPT 909G (KDSP-B1): 23% utilization — low material movement due to supply delay',
      'Eicher Pro 6025 (BMRC-E2): 31% utilization — scheduled for re-task to NH-44X this week',
      'Volvo EC480D (VIZG-P2): 18% utilization — pile driving complete, new task not yet assigned',
      'Combined daily idle cost: ₹72,300',
    ],
    predictedImpact: '₹72.3K/day idle cost. 7-day projection: ₹5.1L avoidable cost.',
  },
  {
    id: 'ALT-011',
    severity: 'medium',
    title: 'Crane Spares Critical Stock — HYD-M3',
    description: 'Only 1 hydraulic pump kit remains in stores for Sany SCC800A crane at HYD-M3. PO-2866 approved for 3 more kits but delivery not until June 27. If the active crane develops any issue before delivery, site will have no spare.',
    department: 'procurement',
    affectedEntity: 'PO-2866 · Atlas Copco India',
    projectId: 'HYD-M3',
    timestamp: '2025-06-26T09:00:00',
    status: 'acknowledged',
    acknowledgedBy: 'Pallavi Reddy',
    evidenceBullets: [
      'Current stock: 1 kit | Reorder point: 2 kits | PO-2866 delivery: June 27',
      'Sany SCC800A crane critical for girder lifting at Station-9 — no alternative on site',
      'PO approved and confirmed. Risk window: 1 day only (today)',
      'Alternative sourcing: Sany dealer (Hyderabad) has 2 kits if emergency',
    ],
    predictedImpact: 'Low probability event but high impact — ₹28K/day crane idle cost if breakdown occurs.',
  },
  {
    id: 'ALT-012',
    severity: 'medium',
    title: 'Near-Miss Safety Incident — Mumbai Coastal Road',
    description: 'A near-miss incident was reported at MUM-CST marine operations zone on June 25 at 14:30. A marine vessel drifted close to the active piling rig during a tide change. No injuries. Root cause: pilot boat communication failure. Formal investigation underway.',
    department: 'safety',
    affectedEntity: 'MUM-CST · Marine Zone Alpha',
    projectId: 'MUM-CST',
    timestamp: '2025-06-25T15:45:00',
    status: 'acknowledged',
    acknowledgedBy: 'Smita Rao',
    evidenceBullets: [
      'Vessel drift distance: 18m from active piling rig. Safe exclusion zone: 25m',
      'Root cause: pilot boat VHF radio failure during tide change maneuver',
      'Emergency stop activated — no structural impact to rig or personnel injury',
      'Safety officer has mandated daily radio check protocol and added secondary signal flares',
    ],
    predictedImpact: 'No direct cost impact. Incident reported to DGMS. Corrective actions under implementation.',
  },
  {
    id: 'ALT-013',
    severity: 'medium',
    title: 'Volvo EC480D Boom Cylinder Seal — High Risk',
    description: 'VLV-EC480-019 at Visakhapatnam Port has a high-risk predictive alert for boom cylinder seal failure. Volvo Connect analysis shows seal degradation pattern consistent with imminent failure. Machine is currently 18% utilized but assigned to berth wall casting next week.',
    department: 'fleet',
    affectedEntity: 'VLV-EC480-019 · VIZG-P2',
    projectId: 'VIZG-P2',
    timestamp: '2025-06-26T05:00:00',
    status: 'new',
    evidenceBullets: [
      'Volvo Connect seal wear index: 8.4/10 (alert threshold: 7.0)',
      'Estimated days to failure: 3-7 days at current hydraulic pressure pattern',
      'Seal replacement cost: ₹35,000. Volvo authorized technician available in Visakhapatnam',
      'Machine scheduled for critical berth casting week of June 30 — must be operational',
    ],
    predictedImpact: '₹24.5K/day idle cost if breaks down during critical casting activity.',
  },
  {
    id: 'ALT-014',
    severity: 'medium',
    title: 'Eicher Pro 6025 Transmission Service Overdue',
    description: 'EIC-PRO6025-011 at BMRC-E2 is 840km past its transmission service interval. Risk level medium. Machine utilization has been low (31%) so impact is limited, but service cannot be deferred beyond this week.',
    department: 'fleet',
    affectedEntity: 'EIC-PRO6025-011 · BMRC-E2',
    projectId: 'BMRC-E2',
    timestamp: '2025-06-25T20:00:00',
    status: 'acknowledged',
    acknowledgedBy: 'Ravi Kumar',
    evidenceBullets: [
      'Transmission service due at 9,000km — currently at 9,120km',
      'Eicher service authorized workshop: 12km from site',
      'Service window: coordinate with low-utilization day (Tuesday or Wednesday)',
      'Estimated downtime: 4-6 hours. Cost: ₹18,000',
    ],
    predictedImpact: 'Preventive — deferral risk is transmission failure costing ₹1.8L and 3 days downtime.',
  },
  {
    id: 'ALT-015',
    severity: 'medium',
    title: 'HYD-M3 Budget at 12.1% Overrun — Trend Worsening',
    description: 'Hyderabad Metro Pkg-3 cost overrun has grown from 5.2% (4 weeks ago) to 12.1% this week. Primary drivers: steel spot purchases (+22% premium), overtime costs due to schedule pressure, and additional scaffolding hire. Finance model projects 14-16% if not arrested.',
    department: 'finance',
    affectedEntity: 'HYD-M3 · Arun Prakash',
    projectId: 'HYD-M3',
    timestamp: '2025-06-26T00:00:00',
    status: 'new',
    evidenceBullets: [
      'Cost overrun trend: 5.2% (Week 19) → 7.4% → 8.1% → 9.3% → 10.5% → 11.2% → 12.1% (Week 25)',
      'Steel spot purchases in Weeks 22-25: 3 transactions at ₹4.2L total premium over contract rate',
      'Overtime hours in June: 1,840 hrs (budget: 400 hrs) — ₹18.4L excess labor cost',
      'Projection: 14-16% overrun if steel supply not normalised within 2 weeks',
    ],
    predictedImpact: 'Contract LD clauses and client relationship at risk if overrun exceeds 15%.',
  },
  {
    id: 'ALT-016',
    severity: 'info',
    title: 'Mumbai Coastal Road — Monthly Progress Report Ready',
    description: 'Monthly progress report for MUM-CST (June 2025) has been generated. Progress: 29% complete, on schedule, cost variance +1.2%. Report is available for MD review and client submission.',
    department: 'operations',
    affectedEntity: 'MUM-CST · Deepak Nambiar',
    projectId: 'MUM-CST',
    timestamp: '2025-06-26T09:30:00',
    status: 'new',
    evidenceBullets: [
      'June 2025 progress: 4.2% monthly (plan: 4.0%) — slightly ahead',
      'Cost at completion estimate: ₹21.58Cr vs ₹21.5Cr budget — margin: ₹7.2L',
      'Workforce: 621 deployed; 0 LTI; 1 near-miss (actioned)',
      'Next milestone: Piling Works complete (August 30, 2025) — on track',
    ],
    predictedImpact: 'No action required. Report for information and client submission.',
  },
  {
    id: 'ALT-017',
    severity: 'info',
    title: 'Chennai Flyover Approaching Completion — 92%',
    description: 'CHN-FLY is at 92% completion, 16 days ahead of planned schedule and 4% under budget. Final road surfacing expected to commence next week. Project set to be NECL\'s fastest completed contract in FY2025-26.',
    department: 'operations',
    affectedEntity: 'CHN-FLY · Karthik Iyer',
    projectId: 'CHN-FLY',
    timestamp: '2025-06-26T08:00:00',
    status: 'new',
    evidenceBullets: [
      'Progress: 92% vs 89% planned — 3% ahead',
      'Cost performance: ₹1.795Cr actual vs ₹1.87Cr budget — 4% under',
      'Completion forecast: July 30 vs planned August 15 — 16 days ahead',
      'Final activity: Road surfacing (1.8km) + safety markings + inspection',
    ],
    predictedImpact: 'Positive — project will release ₹7.4L budget surplus and free crew/equipment for redeployment.',
  },
  {
    id: 'ALT-018',
    severity: 'info',
    title: 'BMRC-E2 Precast Girder Order Confirmed',
    description: 'PO-2857 for 80 precast box girders from Nagarjuna Precast has been approved by Sunita Krishnan. Delivery scheduled August 1. Production tracking integration with Nagarjuna\'s system confirmed.',
    department: 'procurement',
    affectedEntity: 'PO-2857 · Nagarjuna Precast',
    projectId: 'BMRC-E2',
    timestamp: '2025-06-25T14:00:00',
    status: 'resolved',
    acknowledgedBy: 'Sunita Krishnan',
    evidenceBullets: [
      'PO-2857 approved: 80 nos precast box girders, ₹1.43Cr',
      'Production start: June 28 at Nagarjuna Precast yard (Hyderabad)',
      'Delivery: August 1, 2025 — 2 months advance of installation requirement',
      'Quality plan agreed: third-party inspection at casting yard before dispatch',
    ],
    predictedImpact: 'No risk. Advance procurement with quality assurance strengthens delivery confidence.',
  },
  {
    id: 'ALT-019',
    severity: 'info',
    title: 'Fleet Telematics Integration — Sany Remote Added',
    description: 'Sany Remote telematics platform integration completed for 4 Sany machines across the portfolio. Real-time data feeds (fuel, utilization, error codes) now live in NECL Jarvis dashboard.',
    department: 'fleet',
    affectedEntity: 'Portfolio · 4 Sany Machines',
    projectId: 'MUM-CST',
    timestamp: '2025-06-25T11:00:00',
    status: 'resolved',
    evidenceBullets: [
      'Machines integrated: SNY-SY215-003, SNY-SCX1000-007, SNY-SCC800-016, SNY-SRSC600-025',
      'Data latency: <2 minutes (improved from manual daily reporting)',
      'Alerts active: fuel threshold, engine error codes, geofence breaches',
      'Next phase: Komatsu KOMTRAX integration (Q3 2025)',
    ],
    predictedImpact: 'Improved: ₹3.2L monthly fuel waste reduction expected from real-time idle monitoring.',
  },
  {
    id: 'ALT-020',
    severity: 'info',
    title: 'Monthly Payroll Processing Complete — June 2025',
    description: 'June 2025 payroll for 2,444 employees across 8 projects has been processed. Total payroll: ₹8.4Cr. ESI and PF submissions scheduled for June 30 compliance.',
    department: 'hr',
    affectedEntity: 'All Projects · HR Dept',
    projectId: 'MUM-CST',
    timestamp: '2025-06-25T20:00:00',
    status: 'resolved',
    evidenceBullets: [
      'Total payroll: ₹8.4Cr for 2,444 employees across 8 project sites',
      'ESI contribution: ₹28.4L (employer + employee)',
      'PF contribution: ₹72.8L (employer + employee)',
      'Compliance submissions: June 30, 2025 deadline — on track',
    ],
    predictedImpact: 'No action required. Compliance on track.',
  },
]

export function getAlertsByProject(projectId: string): Alert[] {
  return alerts.filter(a => a.projectId === projectId)
}

export function getAlertsByDepartment(dept: string): Alert[] {
  return alerts.filter(a => a.department === dept)
}

export function getAlertsSummary() {
  return {
    critical: alerts.filter(a => a.severity === 'critical').length,
    high: alerts.filter(a => a.severity === 'high').length,
    medium: alerts.filter(a => a.severity === 'medium').length,
    info: alerts.filter(a => a.severity === 'info').length,
    total: alerts.length,
    new: alerts.filter(a => a.status === 'new').length,
  }
}
