export interface OperatorProfile {
  name: string
  machineId: string
  projectId: string
  machineType: string
  attendanceRate: number       // %
  shiftAdherenceRate: number   // % (actual engine-on hours / scheduled shift hours)
  fuelVariancePct: number      // % vs benchmark (negative = efficient, positive = wasteful)
  harshOperationIndex: number  // 0–10 scale (lower is better; >5 = problem)
  certifications: string[]     // e.g. ['IS12285', 'DGFASLI']
  certExpiryDate: string       // ISO date of soonest-expiring cert
  certStatus: 'valid' | 'expiring-soon' | 'expired'
  machineTypes: string[]       // all types this operator is certified for
  idleDaysAssigned: number     // days their current machine has been idle (0 if active)
}

export interface FleetManager {
  name: string
  projectId: string
  machineIds: string[]
  pmComplianceRate: number     // % PMs done on time
  mtbfHours: number            // mean time between failures (hrs) — benchmark 400–600
  avgRepairTATHours: number    // avg breakdown-to-operational hours
  fuelVariancePct: number      // fleet fuel actual vs benchmark %
  breakdownsLast90Days: number
  openWorkOrders: number
  idleCostWeeklyTrend: number[]  // 6 weeks of total weekly idle cost (₹)
}

export interface DeploymentRecommendation {
  id: string
  machineId: string
  machineType: string
  fromProjectId: string
  fromProjectProgress: number   // % complete — high = winding down
  toProjectId: string
  toProjectDelayDays: number    // days behind schedule
  dailyIdleCost: number
  idleDays: number              // how many days it's been idle
  totalIdleBurnSoFar: number    // dailyIdleCost × idleDays
  scheduleRecoveryDays: number  // est. days of schedule recovery if redeployed
  urgency: 'critical' | 'high' | 'medium'
  reason: string
}

export interface MaintenanceForecastEntry {
  machineId: string
  type: string
  projectId: string
  component: string
  riskLevel: string
  estimatedCost: number
  dueDate: string
}

export interface MaintenanceForecast {
  window: '0-30d' | '30-60d' | '60-90d'
  machines: MaintenanceForecastEntry[]
  totalEstimatedCost: number
}

// ─── Operator Profiles (25 entries) ────────────────────────────────────────────

export const operatorProfiles: OperatorProfile[] = [
  {
    name: 'Suresh Babu',
    machineId: 'VLV-EC210-001',
    projectId: 'HYD-M3',
    machineType: 'Excavator',
    attendanceRate: 96,
    shiftAdherenceRate: 91,
    fuelVariancePct: -2.1,
    harshOperationIndex: 2.1,
    certifications: ['IS12285'],
    certExpiryDate: '2027-03-15',
    certStatus: 'valid',
    machineTypes: ['Excavator'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Ramaiah K',
    machineId: 'VLV-EC300-002',
    projectId: 'HYD-M3',
    machineType: 'Excavator',
    attendanceRate: 88,
    shiftAdherenceRate: 78,
    fuelVariancePct: 12.4,
    harshOperationIndex: 6.8,
    certifications: ['IS12285'],
    certExpiryDate: '2026-08-10',
    certStatus: 'expiring-soon',
    machineTypes: ['Excavator'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Naveen G',
    machineId: 'SNY-SY215-003',
    projectId: 'BMRC-E2',
    machineType: 'Excavator',
    attendanceRate: 98,
    shiftAdherenceRate: 94,
    fuelVariancePct: -3.4,
    harshOperationIndex: 1.8,
    certifications: ['IS12285'],
    certExpiryDate: '2027-06-01',
    certStatus: 'valid',
    machineTypes: ['Excavator', 'Wheel Loader'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Bhagwan Das',
    machineId: 'KMT-D375-004',
    projectId: 'NH-44X',
    machineType: 'Bulldozer',
    attendanceRate: 94,
    shiftAdherenceRate: 89,
    fuelVariancePct: 5.2,
    harshOperationIndex: 4.1,
    certifications: ['IS12285'],
    certExpiryDate: '2026-09-20',
    certStatus: 'valid',
    machineTypes: ['Bulldozer'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Yellaiah S',
    machineId: 'TATA-909-005',
    projectId: 'KDSP-B1',
    machineType: 'Tipper',
    attendanceRate: 71,
    shiftAdherenceRate: 68,
    fuelVariancePct: 8.9,
    harshOperationIndex: 5.4,
    certifications: ['IS12285'],
    certExpiryDate: '2025-12-01',
    certStatus: 'expired',
    machineTypes: ['Tipper'],
    idleDaysAssigned: 4,
  },
  {
    name: 'Mahesh K',
    machineId: 'EICH-PRO3015-006',
    projectId: 'KDSP-B1',
    machineType: 'Truck',
    attendanceRate: 92,
    shiftAdherenceRate: 86,
    fuelVariancePct: 3.1,
    harshOperationIndex: 3.2,
    certifications: ['IS12285'],
    certExpiryDate: '2027-01-15',
    certStatus: 'valid',
    machineTypes: ['Truck', 'Tipper'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Rajan Pillai',
    machineId: 'SNY-SCX1000-007',
    projectId: 'MUM-CST',
    machineType: 'Crane',
    attendanceRate: 99,
    shiftAdherenceRate: 97,
    fuelVariancePct: -1.8,
    harshOperationIndex: 1.2,
    certifications: ['IS12285', 'DGFASLI'],
    certExpiryDate: '2026-07-20',
    certStatus: 'expiring-soon',
    machineTypes: ['Crane'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Santosh N',
    machineId: 'VLV-EC210-008',
    projectId: 'MUM-CST',
    machineType: 'Excavator',
    attendanceRate: 95,
    shiftAdherenceRate: 90,
    fuelVariancePct: -0.8,
    harshOperationIndex: 2.4,
    certifications: ['IS12285'],
    certExpiryDate: '2027-04-10',
    certStatus: 'valid',
    machineTypes: ['Excavator'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Venkateswara R',
    machineId: 'KMT-PC490-009',
    projectId: 'RLWY-G4',
    machineType: 'Excavator',
    attendanceRate: 93,
    shiftAdherenceRate: 88,
    fuelVariancePct: 1.2,
    harshOperationIndex: 2.8,
    certifications: ['IS12285'],
    certExpiryDate: '2026-11-30',
    certStatus: 'valid',
    machineTypes: ['Excavator'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Raju B',
    machineId: 'TATA-1918-010',
    projectId: 'NH-44X',
    machineType: 'Tipper',
    attendanceRate: 96,
    shiftAdherenceRate: 92,
    fuelVariancePct: -1.5,
    harshOperationIndex: 1.9,
    certifications: ['IS12285'],
    certExpiryDate: '2027-02-28',
    certStatus: 'valid',
    machineTypes: ['Tipper', 'Truck'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Pradeep M',
    machineId: 'EICH-PRO6025-011',
    projectId: 'BMRC-E2',
    machineType: 'Truck',
    attendanceRate: 82,
    shiftAdherenceRate: 75,
    fuelVariancePct: 7.8,
    harshOperationIndex: 5.1,
    certifications: ['IS12285'],
    certExpiryDate: '2026-12-15',
    certStatus: 'valid',
    machineTypes: ['Truck'],
    idleDaysAssigned: 3,
  },
  {
    name: 'Anil Kumar',
    machineId: 'SNY-SY365-012',
    projectId: 'VIZG-P2',
    machineType: 'Excavator',
    attendanceRate: 97,
    shiftAdherenceRate: 93,
    fuelVariancePct: 2.1,
    harshOperationIndex: 2.6,
    certifications: ['IS12285'],
    certExpiryDate: '2027-08-01',
    certStatus: 'valid',
    machineTypes: ['Excavator', 'Crawler Crane'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Krishna Murthy',
    machineId: 'KMT-WA480-013',
    projectId: 'KDSP-B1',
    machineType: 'Wheel Loader',
    attendanceRate: 91,
    shiftAdherenceRate: 84,
    fuelVariancePct: 4.2,
    harshOperationIndex: 3.8,
    certifications: ['IS12285'],
    certExpiryDate: '2026-10-25',
    certStatus: 'valid',
    machineTypes: ['Wheel Loader'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Dinesh T',
    machineId: 'VLV-L220-014',
    projectId: 'MUM-CST',
    machineType: 'Wheel Loader',
    attendanceRate: 98,
    shiftAdherenceRate: 95,
    fuelVariancePct: -2.9,
    harshOperationIndex: 1.5,
    certifications: ['IS12285'],
    certExpiryDate: '2027-03-20',
    certStatus: 'valid',
    machineTypes: ['Wheel Loader', 'Excavator'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Murugesan P',
    machineId: 'TATA-407-015',
    projectId: 'CHN-FLY',
    machineType: 'Mini Truck',
    attendanceRate: 94,
    shiftAdherenceRate: 88,
    fuelVariancePct: 1.8,
    harshOperationIndex: 2.2,
    certifications: ['IS12285'],
    certExpiryDate: '2027-01-10',
    certStatus: 'valid',
    machineTypes: ['Mini Truck', 'Truck'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Girish Reddy',
    machineId: 'SNY-SCC800-016',
    projectId: 'HYD-M3',
    machineType: 'Crawler Crane',
    attendanceRate: 99,
    shiftAdherenceRate: 98,
    fuelVariancePct: -0.5,
    harshOperationIndex: 1.1,
    certifications: ['IS12285', 'DGFASLI'],
    certExpiryDate: '2026-08-05',
    certStatus: 'expiring-soon',
    machineTypes: ['Crawler Crane', 'Crane'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Damodar P',
    machineId: 'KMT-GD655-017',
    projectId: 'NH-44X',
    machineType: 'Grader',
    attendanceRate: 95,
    shiftAdherenceRate: 91,
    fuelVariancePct: -1.2,
    harshOperationIndex: 2.0,
    certifications: ['IS12285'],
    certExpiryDate: '2027-05-15',
    certStatus: 'valid',
    machineTypes: ['Grader', 'Bulldozer'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Narayana S',
    machineId: 'EICH-PRO8031-018',
    projectId: 'RLWY-G4',
    machineType: 'Truck',
    attendanceRate: 90,
    shiftAdherenceRate: 83,
    fuelVariancePct: 3.6,
    harshOperationIndex: 3.4,
    certifications: ['IS12285'],
    certExpiryDate: '2026-11-20',
    certStatus: 'valid',
    machineTypes: ['Truck'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Srinivas B',
    machineId: 'VLV-EC480-019',
    projectId: 'VIZG-P2',
    machineType: 'Excavator',
    attendanceRate: 78,
    shiftAdherenceRate: 71,
    fuelVariancePct: 14.8,
    harshOperationIndex: 7.2,
    certifications: ['IS12285'],
    certExpiryDate: '2025-09-01',
    certStatus: 'expired',
    machineTypes: ['Excavator'],
    idleDaysAssigned: 6,
  },
  {
    name: 'Hanumaiah B',
    machineId: 'SNY-SP16-020',
    projectId: 'NH-44X',
    machineType: 'Paver',
    attendanceRate: 97,
    shiftAdherenceRate: 95,
    fuelVariancePct: -3.8,
    harshOperationIndex: 1.3,
    certifications: ['IS12285'],
    certExpiryDate: '2027-07-20',
    certStatus: 'valid',
    machineTypes: ['Paver'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Vijay Kumar',
    machineId: 'KMT-HD785-021',
    projectId: 'BMRC-E2',
    machineType: 'Dump Truck',
    attendanceRate: 86,
    shiftAdherenceRate: 79,
    fuelVariancePct: 9.4,
    harshOperationIndex: 6.1,
    certifications: ['IS12285'],
    certExpiryDate: '2026-06-30',
    certStatus: 'expired',
    machineTypes: ['Dump Truck'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Jagan Mohan',
    machineId: 'TATA-3718-022',
    projectId: 'KDSP-B1',
    machineType: 'Concrete Mixer',
    attendanceRate: 93,
    shiftAdherenceRate: 87,
    fuelVariancePct: 0.8,
    harshOperationIndex: 2.3,
    certifications: ['IS12285'],
    certExpiryDate: '2027-02-10',
    certStatus: 'valid',
    machineTypes: ['Concrete Mixer'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Ratan Lal',
    machineId: 'EICH-PRO3015-023',
    projectId: 'MUM-CST',
    machineType: 'Transit Mixer',
    attendanceRate: 96,
    shiftAdherenceRate: 92,
    fuelVariancePct: -1.4,
    harshOperationIndex: 1.8,
    certifications: ['IS12285'],
    certExpiryDate: '2027-04-25',
    certStatus: 'valid',
    machineTypes: ['Transit Mixer', 'Truck'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Senthil Kumar',
    machineId: 'VLV-EC140-024',
    projectId: 'CHN-FLY',
    machineType: 'Excavator',
    attendanceRate: 94,
    shiftAdherenceRate: 90,
    fuelVariancePct: 2.4,
    harshOperationIndex: 2.7,
    certifications: ['IS12285'],
    certExpiryDate: '2026-12-18',
    certStatus: 'valid',
    machineTypes: ['Excavator'],
    idleDaysAssigned: 0,
  },
  {
    name: 'Ashok Nayak',
    machineId: 'SNY-SRSC600-025',
    projectId: 'VIZG-P2',
    machineType: 'Reach Stacker',
    attendanceRate: 97,
    shiftAdherenceRate: 94,
    fuelVariancePct: -0.9,
    harshOperationIndex: 1.6,
    certifications: ['IS12285', 'DGFASLI'],
    certExpiryDate: '2027-01-08',
    certStatus: 'valid',
    machineTypes: ['Reach Stacker', 'Crane'],
    idleDaysAssigned: 0,
  },
]

// ─── Fleet Managers (8 entries) ────────────────────────────────────────────────

export const fleetManagers: FleetManager[] = [
  {
    name: 'Ramesh Iyengar',
    projectId: 'HYD-M3',
    machineIds: ['VLV-EC210-001', 'VLV-EC300-002', 'SNY-SCC800-016'],
    pmComplianceRate: 72,
    mtbfHours: 320,
    avgRepairTATHours: 28,
    fuelVariancePct: 4.8,
    breakdownsLast90Days: 4,
    openWorkOrders: 3,
    idleCostWeeklyTrend: [42000, 45000, 52000, 58000, 64000, 68200],
  },
  {
    name: 'Vinod Sharma',
    projectId: 'BMRC-E2',
    machineIds: ['SNY-SY215-003', 'EICH-PRO6025-011', 'KMT-HD785-021'],
    pmComplianceRate: 61,
    mtbfHours: 280,
    avgRepairTATHours: 34,
    fuelVariancePct: 7.2,
    breakdownsLast90Days: 6,
    openWorkOrders: 5,
    idleCostWeeklyTrend: [28000, 35000, 42100, 42100, 42100, 42100],
  },
  {
    name: 'Shankar Prasad',
    projectId: 'NH-44X',
    machineIds: ['KMT-D375-004', 'TATA-1918-010', 'KMT-GD655-017', 'SNY-SP16-020'],
    pmComplianceRate: 94,
    mtbfHours: 580,
    avgRepairTATHours: 8,
    fuelVariancePct: 1.4,
    breakdownsLast90Days: 1,
    openWorkOrders: 0,
    idleCostWeeklyTrend: [22000, 20000, 18000, 16000, 15000, 14000],
  },
  {
    name: 'Ravi Chakravarti',
    projectId: 'KDSP-B1',
    machineIds: ['TATA-909-005', 'EICH-PRO3015-006', 'KMT-WA480-013', 'TATA-3718-022'],
    pmComplianceRate: 58,
    mtbfHours: 340,
    avgRepairTATHours: 18,
    fuelVariancePct: 6.1,
    breakdownsLast90Days: 3,
    openWorkOrders: 4,
    idleCostWeeklyTrend: [28000, 31000, 34000, 33600, 33800, 33600],
  },
  {
    name: 'Anbu Chelvan',
    projectId: 'CHN-FLY',
    machineIds: ['TATA-407-015', 'VLV-EC140-024'],
    pmComplianceRate: 88,
    mtbfHours: 520,
    avgRepairTATHours: 6,
    fuelVariancePct: 2.1,
    breakdownsLast90Days: 0,
    openWorkOrders: 0,
    idleCostWeeklyTrend: [14000, 12000, 11600, 11600, 11600, 11600],
  },
  {
    name: 'Prashanth Hegde',
    projectId: 'MUM-CST',
    machineIds: ['SNY-SCX1000-007', 'VLV-EC210-008', 'VLV-L220-014', 'EICH-PRO3015-023'],
    pmComplianceRate: 91,
    mtbfHours: 490,
    avgRepairTATHours: 12,
    fuelVariancePct: -0.8,
    breakdownsLast90Days: 1,
    openWorkOrders: 1,
    idleCostWeeklyTrend: [67200, 68000, 67400, 67200, 67100, 67200],
  },
  {
    name: 'Subramaniam V',
    projectId: 'RLWY-G4',
    machineIds: ['KMT-PC490-009', 'EICH-PRO8031-018'],
    pmComplianceRate: 79,
    mtbfHours: 420,
    avgRepairTATHours: 14,
    fuelVariancePct: 2.8,
    breakdownsLast90Days: 2,
    openWorkOrders: 1,
    idleCostWeeklyTrend: [24300, 24300, 24300, 24300, 24300, 24300],
  },
  {
    name: 'Geetanath Panda',
    projectId: 'VIZG-P2',
    machineIds: ['SNY-SY365-012', 'VLV-EC480-019', 'SNY-SRSC600-025'],
    pmComplianceRate: 68,
    mtbfHours: 360,
    avgRepairTATHours: 22,
    fuelVariancePct: 8.4,
    breakdownsLast90Days: 3,
    openWorkOrders: 2,
    idleCostWeeklyTrend: [31500, 33000, 35000, 36500, 38500, 45000],
  },
]

// ─── Deployment Recommendations (4 entries) ────────────────────────────────────

export const deploymentRecommendations: DeploymentRecommendation[] = [
  {
    id: 'dr-1',
    machineId: 'VLV-EC480-019',
    machineType: 'Excavator',
    fromProjectId: 'VIZG-P2',
    fromProjectProgress: 38,
    toProjectId: 'KDSP-B1',
    toProjectDelayDays: 49,
    dailyIdleCost: 24500,
    idleDays: 6,
    totalIdleBurnSoFar: 147000,
    scheduleRecoveryDays: 8,
    urgency: 'critical',
    reason: 'Idle 6 days at VIZG-P2. KDSP-B1 is 49d behind schedule — redeploying this excavator recovers est. 8 days.',
  },
  {
    id: 'dr-2',
    machineId: 'EICH-PRO6025-011',
    machineType: 'Truck',
    fromProjectId: 'BMRC-E2',
    fromProjectProgress: 43,
    toProjectId: 'RLWY-G4',
    toProjectDelayDays: 15,
    dailyIdleCost: 4100,
    idleDays: 3,
    totalIdleBurnSoFar: 12300,
    scheduleRecoveryDays: 4,
    urgency: 'high',
    reason: 'Idle 3 days at BMRC-E2. RLWY-G4 needs material haulage trucks for ballast work.',
  },
  {
    id: 'dr-3',
    machineId: 'VLV-EC140-024',
    machineType: 'Excavator',
    fromProjectId: 'CHN-FLY',
    fromProjectProgress: 92,
    toProjectId: 'HYD-M3',
    toProjectDelayDays: 77,
    dailyIdleCost: 9800,
    idleDays: 0,
    totalIdleBurnSoFar: 0,
    scheduleRecoveryDays: 12,
    urgency: 'high',
    reason: 'CHN-FLY is 92% complete. Pre-emptive redeployment to HYD-M3 (77d behind) recovers est. 12 days. Machine still active — plan mobilisation now.',
  },
  {
    id: 'dr-4',
    machineId: 'TATA-407-015',
    machineType: 'Mini Truck',
    fromProjectId: 'CHN-FLY',
    fromProjectProgress: 92,
    toProjectId: 'MUM-CST',
    toProjectDelayDays: 0,
    dailyIdleCost: 1800,
    idleDays: 0,
    totalIdleBurnSoFar: 0,
    scheduleRecoveryDays: 2,
    urgency: 'medium',
    reason: 'CHN-FLY winding down. MUM-CST deck slab phase begins July — extra light transport needed.',
  },
]

// ─── Maintenance Forecast (3 windows) ──────────────────────────────────────────

export const maintenanceForecast: MaintenanceForecast[] = [
  {
    window: '0-30d',
    machines: [
      { machineId: 'VLV-EC300-002', type: 'Excavator', projectId: 'HYD-M3', component: 'Hydraulic Pump', riskLevel: 'critical', estimatedCost: 1200000, dueDate: '2026-06-28' },
      { machineId: 'KMT-HD785-021', type: 'Dump Truck', projectId: 'BMRC-E2', component: 'Rear Axle Bearing', riskLevel: 'critical', estimatedCost: 1500000, dueDate: '2026-06-27' },
      { machineId: 'TATA-909-005', type: 'Tipper', projectId: 'KDSP-B1', component: 'Brake System', riskLevel: 'medium', estimatedCost: 180000, dueDate: '2026-07-05' },
      { machineId: 'VLV-EC480-019', type: 'Excavator', projectId: 'VIZG-P2', component: 'Boom Cylinder Seal', riskLevel: 'high', estimatedCost: 420000, dueDate: '2026-07-08' },
      { machineId: 'EICH-PRO6025-011', type: 'Truck', projectId: 'BMRC-E2', component: 'Transmission', riskLevel: 'medium', estimatedCost: 220000, dueDate: '2026-07-18' },
      { machineId: 'SNY-SCX1000-007', type: 'Crane', projectId: 'MUM-CST', component: 'Wire Rope Assembly', riskLevel: 'medium', estimatedCost: 280000, dueDate: '2026-07-22' },
    ],
    totalEstimatedCost: 3800000,
  },
  {
    window: '30-60d',
    machines: [
      { machineId: 'VLV-L220-014', type: 'Wheel Loader', projectId: 'MUM-CST', component: 'Steering Cylinder', riskLevel: 'medium', estimatedCost: 150000, dueDate: '2026-07-30' },
      { machineId: 'SNY-SY365-012', type: 'Excavator', projectId: 'VIZG-P2', component: 'Bucket Teeth', riskLevel: 'low', estimatedCost: 60000, dueDate: '2026-08-05' },
      { machineId: 'EICH-PRO8031-018', type: 'Truck', projectId: 'RLWY-G4', component: 'Clutch System', riskLevel: 'medium', estimatedCost: 140000, dueDate: '2026-08-14' },
      { machineId: 'VLV-EC210-008', type: 'Excavator', projectId: 'MUM-CST', component: 'Cooling System', riskLevel: 'low', estimatedCost: 45000, dueDate: '2026-08-15' },
      { machineId: 'SNY-SCC800-016', type: 'Crawler Crane', projectId: 'HYD-M3', component: 'Slewing Ring', riskLevel: 'low', estimatedCost: 380000, dueDate: '2026-08-22' },
      { machineId: 'VLV-EC140-024', type: 'Excavator', projectId: 'CHN-FLY', component: 'Bucket Pin', riskLevel: 'low', estimatedCost: 35000, dueDate: '2026-08-28' },
    ],
    totalEstimatedCost: 810000,
  },
  {
    window: '60-90d',
    machines: [
      { machineId: 'EICH-PRO3015-006', type: 'Truck', projectId: 'KDSP-B1', component: 'Engine Oil System', riskLevel: 'low', estimatedCost: 25000, dueDate: '2026-08-30' },
      { machineId: 'KMT-PC490-009', type: 'Excavator', projectId: 'RLWY-G4', component: 'Final Drive', riskLevel: 'low', estimatedCost: 280000, dueDate: '2026-09-01' },
      { machineId: 'KMT-WA480-013', type: 'Wheel Loader', projectId: 'KDSP-B1', component: 'Axle Seals', riskLevel: 'low', estimatedCost: 55000, dueDate: '2026-09-12' },
      { machineId: 'SNY-SRSC600-025', type: 'Reach Stacker', projectId: 'VIZG-P2', component: 'Spreader Frame', riskLevel: 'medium', estimatedCost: 320000, dueDate: '2026-09-18' },
    ],
    totalEstimatedCost: 680000,
  },
]
