export type AttritionRisk = 'low' | 'medium' | 'high'
export type Department = 'operations' | 'procurement' | 'fleet' | 'finance' | 'hr' | 'engineering' | 'safety'

export interface Employee {
  id: string
  name: string
  role: string
  department: Department
  projectId: string
  attendance: number
  productivity: number
  productivityVsPlan: number
  attritionRisk: AttritionRisk
  skills: string[]
  lastReview: string
  yearsExperience: number
  trend: 'up' | 'down' | 'stable'
  coachingSuggestion: string
  salary: number
  location: string
}

export const employees: Employee[] = [
  {
    id: 'EMP-001',
    name: 'Rajesh Nair',
    role: 'Project Manager',
    department: 'engineering',
    projectId: 'HYD-M3',
    attendance: 98,
    productivity: 82,
    productivityVsPlan: -8,
    attritionRisk: 'low',
    skills: ['Project Planning', 'Risk Management', 'Stakeholder Engagement', 'MS Project'],
    lastReview: '2025-04-15',
    yearsExperience: 18,
    trend: 'stable',
    coachingSuggestion: 'Explore delegation strategies to reduce direct workload; consider a deputy PM for milestone tracking.',
    salary: 2800000,
    location: 'Hyderabad',
  },
  {
    id: 'EMP-002',
    name: 'Sunita Krishnan',
    role: 'Project Manager',
    department: 'engineering',
    projectId: 'BMRC-E2',
    attendance: 96,
    productivity: 91,
    productivityVsPlan: 3,
    attritionRisk: 'low',
    skills: ['Metro Rail', 'FIDIC Contracts', 'Primavera P6', 'Quality Management'],
    lastReview: '2025-03-20',
    yearsExperience: 14,
    trend: 'up',
    coachingSuggestion: 'Strong performer. Encourage cross-project mentoring to share metro expertise with Hyderabad team.',
    salary: 2600000,
    location: 'Bengaluru',
  },
  {
    id: 'EMP-003',
    name: 'Anand Sharma',
    role: 'Project Manager',
    department: 'engineering',
    projectId: 'NH-44X',
    attendance: 94,
    productivity: 93,
    productivityVsPlan: 6,
    attritionRisk: 'low',
    skills: ['Highway Engineering', 'NHAI Standards', 'IRC Codes', 'EHS Management'],
    lastReview: '2025-05-10',
    yearsExperience: 16,
    trend: 'up',
    coachingSuggestion: 'Ahead of plan. Leverage this success to document best practices for other highway projects.',
    salary: 2500000,
    location: 'Nagpur',
  },
  {
    id: 'EMP-004',
    name: 'Priya Menon',
    role: 'Site Manager',
    department: 'engineering',
    projectId: 'KDSP-B1',
    attendance: 92,
    productivity: 78,
    productivityVsPlan: -12,
    attritionRisk: 'medium',
    skills: ['Irrigation Engineering', 'Hydraulic Structures', 'AutoCAD', 'Site Supervision'],
    lastReview: '2025-04-01',
    yearsExperience: 10,
    trend: 'down',
    coachingSuggestion: 'Consider weekly touchpoints with central procurement to resolve supply chain issues causing productivity dip.',
    salary: 1800000,
    location: 'Medigadda',
  },
  {
    id: 'EMP-005',
    name: 'Karthik Iyer',
    role: 'Site Manager',
    department: 'engineering',
    projectId: 'CHN-FLY',
    attendance: 97,
    productivity: 96,
    productivityVsPlan: 9,
    attritionRisk: 'low',
    skills: ['Urban Infrastructure', 'Traffic Management', 'Structural Design', 'Quality Control'],
    lastReview: '2025-05-22',
    yearsExperience: 12,
    trend: 'up',
    coachingSuggestion: 'Exceptional performance. Nominate for Senior PM fast-track based on Chennai flyover delivery.',
    salary: 1900000,
    location: 'Chennai',
  },
  {
    id: 'EMP-006',
    name: 'Deepak Nambiar',
    role: 'Project Director',
    department: 'engineering',
    projectId: 'MUM-CST',
    attendance: 91,
    productivity: 88,
    productivityVsPlan: 1,
    attritionRisk: 'low',
    skills: ['Marine Engineering', 'Coastal Structures', 'Contract Management', 'FIDIC Conditions'],
    lastReview: '2025-03-05',
    yearsExperience: 22,
    trend: 'stable',
    coachingSuggestion: 'On track on a complex marine project. Ensure succession planning given project criticality.',
    salary: 4200000,
    location: 'Mumbai',
  },
  {
    id: 'EMP-007',
    name: 'Venkat Rao',
    role: 'Project Manager',
    department: 'engineering',
    projectId: 'RLWY-G4',
    attendance: 89,
    productivity: 74,
    productivityVsPlan: -18,
    attritionRisk: 'high',
    skills: ['Railway Engineering', 'Track Geometry', 'OHE Design', 'CRS Coordination'],
    lastReview: '2025-02-28',
    yearsExperience: 9,
    trend: 'down',
    coachingSuggestion: 'Struggling with multi-agency coordination. Consider pairing with a senior technical advisor. Conduct a 1:1 wellbeing check.',
    salary: 1600000,
    location: 'Guntakal',
  },
  {
    id: 'EMP-008',
    name: 'Sarita Patel',
    role: 'Project Manager',
    department: 'engineering',
    projectId: 'VIZG-P2',
    attendance: 95,
    productivity: 86,
    productivityVsPlan: -2,
    attritionRisk: 'low',
    skills: ['Port Engineering', 'Marine Geotechnics', 'Dredging', 'Material Handling'],
    lastReview: '2025-04-20',
    yearsExperience: 13,
    trend: 'stable',
    coachingSuggestion: 'Well-balanced performance on a technically complex port project. Explore additional training in maritime law and port regulations.',
    salary: 2400000,
    location: 'Visakhapatnam',
  },
  {
    id: 'EMP-009',
    name: 'Ravi Kumar',
    role: 'Fleet Manager',
    department: 'fleet',
    projectId: 'HYD-M3',
    attendance: 99,
    productivity: 88,
    productivityVsPlan: 2,
    attritionRisk: 'low',
    skills: ['Fleet Management', 'Preventive Maintenance', 'Telematics', 'Fuel Optimization'],
    lastReview: '2025-05-01',
    yearsExperience: 15,
    trend: 'up',
    coachingSuggestion: 'High performer with strong telematics adoption. Share fleet utilization practices across all projects.',
    salary: 1800000,
    location: 'Hyderabad',
  },
  {
    id: 'EMP-010',
    name: 'Suresh Babu',
    role: 'Equipment Operator',
    department: 'fleet',
    projectId: 'HYD-M3',
    attendance: 94,
    productivity: 87,
    productivityVsPlan: 4,
    attritionRisk: 'low',
    skills: ['Excavator Operation', 'Volvo EC Series', 'Safe Lifting', 'Daily Checks'],
    lastReview: '2025-03-15',
    yearsExperience: 8,
    trend: 'stable',
    coachingSuggestion: 'Reliable operator. Eligible for senior operator certification.',
    salary: 480000,
    location: 'Hyderabad',
  },
  {
    id: 'EMP-011',
    name: 'Pallavi Reddy',
    role: 'Procurement Manager',
    department: 'procurement',
    projectId: 'HYD-M3',
    attendance: 96,
    productivity: 79,
    productivityVsPlan: -11,
    attritionRisk: 'medium',
    skills: ['Vendor Management', 'Contract Negotiation', 'SAP Ariba', 'GST Compliance'],
    lastReview: '2025-04-08',
    yearsExperience: 7,
    trend: 'down',
    coachingSuggestion: 'PO delays on steel procurement affecting project. Recommend escalation protocol training and vendor diversification review.',
    salary: 1400000,
    location: 'Hyderabad',
  },
  {
    id: 'EMP-012',
    name: 'Arun Prakash',
    role: 'Finance Controller',
    department: 'finance',
    projectId: 'HYD-M3',
    attendance: 97,
    productivity: 84,
    productivityVsPlan: -1,
    attritionRisk: 'low',
    skills: ['Project Accounting', 'Cost Control', 'Xpedeon ERP', 'IFRS Standards'],
    lastReview: '2025-05-12',
    yearsExperience: 11,
    trend: 'stable',
    coachingSuggestion: 'Steady performer. Build dashboard-based reporting capability to improve management visibility.',
    salary: 1600000,
    location: 'Hyderabad',
  },
  {
    id: 'EMP-013',
    name: 'Kavitha Nair',
    role: 'HR Business Partner',
    department: 'hr',
    projectId: 'MUM-CST',
    attendance: 98,
    productivity: 92,
    productivityVsPlan: 5,
    attritionRisk: 'low',
    skills: ['Talent Management', 'Labour Compliance', 'SAP SuccessFactors', 'Workforce Planning'],
    lastReview: '2025-04-25',
    yearsExperience: 9,
    trend: 'up',
    coachingSuggestion: 'Strong HRBP. Consider transition to Regional HR Head role in 12-18 months.',
    salary: 1500000,
    location: 'Mumbai',
  },
  {
    id: 'EMP-014',
    name: 'Mohammed Shareef',
    role: 'Civil Engineer',
    department: 'engineering',
    projectId: 'KDSP-B1',
    attendance: 88,
    productivity: 72,
    productivityVsPlan: -18,
    attritionRisk: 'high',
    skills: ['Irrigation Structures', 'Hydrological Design', 'AutoCAD Civil 3D', 'Concrete Technology'],
    lastReview: '2025-03-10',
    yearsExperience: 5,
    trend: 'down',
    coachingSuggestion: 'Performance dip possibly linked to remote location and limited team support. Recommend buddy pairing with a senior engineer.',
    salary: 780000,
    location: 'Medigadda',
  },
  {
    id: 'EMP-015',
    name: 'Smita Rao',
    role: 'Safety Officer',
    department: 'safety',
    projectId: 'MUM-CST',
    attendance: 99,
    productivity: 94,
    productivityVsPlan: 7,
    attritionRisk: 'low',
    skills: ['EHS Management', 'NEBOSH GCE', 'Incident Investigation', 'Safety Audits'],
    lastReview: '2025-05-18',
    yearsExperience: 12,
    trend: 'up',
    coachingSuggestion: 'Zero LTI maintained for 8 months. Recommend external recognition submission for safety excellence.',
    salary: 1200000,
    location: 'Mumbai',
  },
  {
    id: 'EMP-016',
    name: 'Girish Reddy',
    role: 'Crane Operator',
    department: 'fleet',
    projectId: 'HYD-M3',
    attendance: 91,
    productivity: 83,
    productivityVsPlan: 0,
    attritionRisk: 'medium',
    skills: ['Crawler Crane', 'Sany SCC Series', 'Rigging', 'Load Chart Reading'],
    lastReview: '2025-04-10',
    yearsExperience: 11,
    trend: 'stable',
    coachingSuggestion: 'Competent operator. Attendance dip in last 4 weeks — check if personal support is needed.',
    salary: 540000,
    location: 'Hyderabad',
  },
  {
    id: 'EMP-017',
    name: 'Vijay Kumar',
    role: 'Equipment Operator',
    department: 'fleet',
    projectId: 'BMRC-E2',
    attendance: 85,
    productivity: 0,
    productivityVsPlan: -100,
    attritionRisk: 'high',
    skills: ['Dump Truck', 'Komatsu HD Series', 'Off-road Driving'],
    lastReview: '2025-02-15',
    yearsExperience: 6,
    trend: 'down',
    coachingSuggestion: 'Currently assigned to maintenance. Follow up on equipment repair timeline and reassign to alternate machine by next week.',
    salary: 420000,
    location: 'Bengaluru',
  },
  {
    id: 'EMP-018',
    name: 'Naveena S',
    role: 'Procurement Executive',
    department: 'procurement',
    projectId: 'BMRC-E2',
    attendance: 94,
    productivity: 86,
    productivityVsPlan: 2,
    attritionRisk: 'low',
    skills: ['Vendor Onboarding', 'Purchase Order Management', 'Tally ERP', 'GRN Processing'],
    lastReview: '2025-05-08',
    yearsExperience: 4,
    trend: 'up',
    coachingSuggestion: 'Improving trend on PO processing times. Enroll in advanced supply chain certification.',
    salary: 680000,
    location: 'Bengaluru',
  },
  {
    id: 'EMP-019',
    name: 'Santosh Narayan',
    role: 'Operations Engineer',
    department: 'operations',
    projectId: 'MUM-CST',
    attendance: 93,
    productivity: 89,
    productivityVsPlan: 4,
    attritionRisk: 'low',
    skills: ['Marine Operations', 'Dredging Supervision', 'Hydrographic Survey', 'Diving Operations'],
    lastReview: '2025-04-28',
    yearsExperience: 8,
    trend: 'stable',
    coachingSuggestion: 'Reliable operations specialist on a complex marine site. Consider for senior ops role when Vizag Berth-2 ramps up.',
    salary: 1100000,
    location: 'Mumbai',
  },
  {
    id: 'EMP-020',
    name: 'Ramaiah Krishnappa',
    role: 'Equipment Operator',
    department: 'fleet',
    projectId: 'HYD-M3',
    attendance: 80,
    productivity: 0,
    productivityVsPlan: -100,
    attritionRisk: 'high',
    skills: ['Excavator Operation', 'Volvo EC300', 'Ground Conditions Assessment'],
    lastReview: '2025-01-20',
    yearsExperience: 14,
    trend: 'down',
    coachingSuggestion: 'Equipment in maintenance mode. Connect with operator on reassignment and check on wellbeing — extended idle periods can be demotivating.',
    salary: 480000,
    location: 'Hyderabad',
  },
  {
    id: 'EMP-021',
    name: 'Divya Lakshmanan',
    role: 'Finance Analyst',
    department: 'finance',
    projectId: 'BMRC-E2',
    attendance: 97,
    productivity: 91,
    productivityVsPlan: 6,
    attritionRisk: 'low',
    skills: ['Financial Modelling', 'Cost Variance Analysis', 'Power BI', 'Project EVM'],
    lastReview: '2025-05-20',
    yearsExperience: 5,
    trend: 'up',
    coachingSuggestion: 'Strong analytical skills. Leverage Power BI capability to build real-time cost dashboards for project team.',
    salary: 1100000,
    location: 'Bengaluru',
  },
  {
    id: 'EMP-022',
    name: 'Arjun Pillai',
    role: 'QA/QC Engineer',
    department: 'engineering',
    projectId: 'NH-44X',
    attendance: 96,
    productivity: 90,
    productivityVsPlan: 5,
    attritionRisk: 'low',
    skills: ['Materials Testing', 'IRC Standards', 'NDT Methods', 'Lab Management'],
    lastReview: '2025-04-15',
    yearsExperience: 7,
    trend: 'up',
    coachingSuggestion: 'Excellent quality records on highway project. Consider for QA Head position.',
    salary: 980000,
    location: 'Nagpur',
  },
  {
    id: 'EMP-023',
    name: 'Sreedhara Rao',
    role: 'Surveyor',
    department: 'operations',
    projectId: 'RLWY-G4',
    attendance: 91,
    productivity: 77,
    productivityVsPlan: -8,
    attritionRisk: 'medium',
    skills: ['Total Station', 'DGPS Survey', 'Levelling', 'Railway Alignment'],
    lastReview: '2025-03-22',
    yearsExperience: 12,
    trend: 'down',
    coachingSuggestion: 'Productivity dip due to difficult track alignment conditions. Provide additional survey equipment support.',
    salary: 720000,
    location: 'Guntakal',
  },
  {
    id: 'EMP-024',
    name: 'Neha Kulkarni',
    role: 'HR Executive',
    department: 'hr',
    projectId: 'KDSP-B1',
    attendance: 93,
    productivity: 85,
    productivityVsPlan: -2,
    attritionRisk: 'medium',
    skills: ['Payroll Processing', 'Labour Welfare', 'Compliance Audits', 'ESI/PF'],
    lastReview: '2025-05-05',
    yearsExperience: 4,
    trend: 'stable',
    coachingSuggestion: 'Handling remote site HR singlehandedly. Consider adding contract HR support to prevent burnout.',
    salary: 620000,
    location: 'Medigadda',
  },
  {
    id: 'EMP-025',
    name: 'Rajan Pillai',
    role: 'Crane Operator',
    department: 'fleet',
    projectId: 'MUM-CST',
    attendance: 98,
    productivity: 94,
    productivityVsPlan: 8,
    attritionRisk: 'low',
    skills: ['Marine Crane', 'Sany SCX Series', 'Offshore Rigging', 'Load Management'],
    lastReview: '2025-05-14',
    yearsExperience: 16,
    trend: 'up',
    coachingSuggestion: 'Exemplary marine crane operator. Mentor junior operators on the team.',
    salary: 580000,
    location: 'Mumbai',
  },
  {
    id: 'EMP-026',
    name: 'Shankar Gupta',
    role: 'Store Keeper',
    department: 'procurement',
    projectId: 'KDSP-B1',
    attendance: 86,
    productivity: 73,
    productivityVsPlan: -14,
    attritionRisk: 'high',
    skills: ['Inventory Management', 'Material Reconciliation', 'Bin Card Maintenance'],
    lastReview: '2025-02-10',
    yearsExperience: 6,
    trend: 'down',
    coachingSuggestion: 'Stock discrepancies increasing. Conduct store audit and retrain on inventory procedures. Check on remote posting challenges.',
    salary: 380000,
    location: 'Medigadda',
  },
  {
    id: 'EMP-027',
    name: 'Lavanya S',
    role: 'Safety Officer',
    department: 'safety',
    projectId: 'HYD-M3',
    attendance: 99,
    productivity: 88,
    productivityVsPlan: 2,
    attritionRisk: 'low',
    skills: ['Site Safety Audits', 'PTW System', 'Incident Reporting', 'Tool Box Talks'],
    lastReview: '2025-05-08',
    yearsExperience: 7,
    trend: 'stable',
    coachingSuggestion: 'Consistent safety performance. Near-miss reporting improvements attributable to her awareness campaigns.',
    salary: 980000,
    location: 'Hyderabad',
  },
  {
    id: 'EMP-028',
    name: 'Babu Narayanan',
    role: 'Civil Foreman',
    department: 'operations',
    projectId: 'VIZG-P2',
    attendance: 94,
    productivity: 84,
    productivityVsPlan: 1,
    attritionRisk: 'low',
    skills: ['Concrete Placement', 'Reinforcement Supervision', 'Port Structures', 'Marine Concrete'],
    lastReview: '2025-04-18',
    yearsExperience: 18,
    trend: 'stable',
    coachingSuggestion: 'Experienced foreman with deep port structure knowledge. Formal recognition for tenure and knowledge transfer would help retention.',
    salary: 620000,
    location: 'Visakhapatnam',
  },
  {
    id: 'EMP-029',
    name: 'Preethi Sundaram',
    role: 'Finance Manager',
    department: 'finance',
    projectId: 'MUM-CST',
    attendance: 96,
    productivity: 90,
    productivityVsPlan: 3,
    attritionRisk: 'low',
    skills: ['Project Finance', 'Budget Management', 'SAP FICO', 'CMA Reports'],
    lastReview: '2025-03-28',
    yearsExperience: 13,
    trend: 'up',
    coachingSuggestion: 'Excellent budget management on the largest project in the portfolio. Groom for CFO track.',
    salary: 2200000,
    location: 'Mumbai',
  },
  {
    id: 'EMP-030',
    name: 'Rahul Verma',
    role: 'IT / Systems Engineer',
    department: 'operations',
    projectId: 'HYD-M3',
    attendance: 97,
    productivity: 92,
    productivityVsPlan: 7,
    attritionRisk: 'low',
    skills: ['Xpedeon ERP Admin', 'Network Setup', 'CCTV Systems', 'IT Support'],
    lastReview: '2025-05-28',
    yearsExperience: 6,
    trend: 'up',
    coachingSuggestion: 'Strong technical performer. Involve in Jarvis AI integration project for ERP data feeds.',
    salary: 860000,
    location: 'Hyderabad',
  },
]

export function getEmployeesByProject(projectId: string): Employee[] {
  return employees.filter(e => e.projectId === projectId)
}

export function getHRSummary() {
  const total = employees.length
  const active = employees.filter(e => e.attendance > 0).length
  const avgAttendance = Math.round(employees.reduce((s, e) => s + e.attendance, 0) / total)
  const highAttrition = employees.filter(e => e.attritionRisk === 'high').length
  const mediumAttrition = employees.filter(e => e.attritionRisk === 'medium').length
  const attritionIndex = ((highAttrition * 3 + mediumAttrition * 1.5) / total * 2).toFixed(1)
  return { total: 2444, active, avgAttendance, highAttrition, mediumAttrition, attritionIndex: parseFloat(attritionIndex) }
}
