export type POStatus = 'pending' | 'approved' | 'delayed' | 'received'
export type ProcurementCategory = 'steel' | 'cement' | 'fuel' | 'equipment' | 'electrical' | 'aggregate' | 'formwork'

export interface PurchaseOrder {
  id: string
  item: string
  vendor: string
  category: ProcurementCategory
  poValue: number
  gstRate: number
  gstAmount: number
  totalValue: number
  status: POStatus
  expectedDelivery: string
  projectId: string
  stockLevel: number
  stockUnit: string
  reorderPoint: number
  stockoutRisk: number // days until stockout
  quantity: number
  quantityUnit: string
  raisedDate: string
  approvedBy?: string
}

export const purchaseOrders: PurchaseOrder[] = [
  {
    id: 'PO-2847',
    item: 'TMT Steel Bars (Fe-500D)',
    vendor: 'JSW Steel Ltd',
    category: 'steel',
    poValue: 4280000,
    gstRate: 18,
    gstAmount: 770400,
    totalValue: 5050400,
    status: 'delayed',
    expectedDelivery: '2025-06-20',
    projectId: 'HYD-M3',
    stockLevel: 42,
    stockUnit: 'MT',
    reorderPoint: 80,
    stockoutRisk: 4,
    quantity: 200,
    quantityUnit: 'MT',
    raisedDate: '2025-06-01',
    approvedBy: 'Rajesh Nair',
  },
  {
    id: 'PO-2848',
    item: 'OPC 53 Grade Cement',
    vendor: 'ACC Ltd',
    category: 'cement',
    poValue: 1840000,
    gstRate: 28,
    gstAmount: 515200,
    totalValue: 2355200,
    status: 'received',
    expectedDelivery: '2025-06-15',
    projectId: 'HYD-M3',
    stockLevel: 580,
    stockUnit: 'bags',
    reorderPoint: 300,
    stockoutRisk: 18,
    quantity: 2000,
    quantityUnit: 'bags',
    raisedDate: '2025-06-03',
    approvedBy: 'Rajesh Nair',
  },
  {
    id: 'PO-2849',
    item: 'HSD Diesel (Bulk)',
    vendor: 'HPCL Dealers Pvt Ltd',
    category: 'fuel',
    poValue: 920000,
    gstRate: 0,
    gstAmount: 0,
    totalValue: 920000,
    status: 'approved',
    expectedDelivery: '2025-06-28',
    projectId: 'HYD-M3',
    stockLevel: 8200,
    stockUnit: 'litres',
    reorderPoint: 5000,
    stockoutRisk: 7,
    quantity: 10000,
    quantityUnit: 'litres',
    raisedDate: '2025-06-20',
    approvedBy: 'Rajesh Nair',
  },
  {
    id: 'PO-2850',
    item: 'Pre-stressed Concrete Sleepers',
    vendor: 'Patil Rail Infrastructure',
    category: 'equipment',
    poValue: 6750000,
    gstRate: 12,
    gstAmount: 810000,
    totalValue: 7560000,
    status: 'pending',
    expectedDelivery: '2025-07-15',
    projectId: 'RLWY-G4',
    stockLevel: 420,
    stockUnit: 'nos',
    reorderPoint: 500,
    stockoutRisk: 12,
    quantity: 2000,
    quantityUnit: 'nos',
    raisedDate: '2025-06-22',
  },
  {
    id: 'PO-2851',
    item: 'Structural Steel (IS 2062)',
    vendor: 'Tata Steel Ltd',
    category: 'steel',
    poValue: 8420000,
    gstRate: 18,
    gstAmount: 1515600,
    totalValue: 9935600,
    status: 'approved',
    expectedDelivery: '2025-07-05',
    projectId: 'MUM-CST',
    stockLevel: 185,
    stockUnit: 'MT',
    reorderPoint: 200,
    stockoutRisk: 21,
    quantity: 400,
    quantityUnit: 'MT',
    raisedDate: '2025-06-10',
    approvedBy: 'Deepak Nambiar',
  },
  {
    id: 'PO-2852',
    item: 'Reinforcement Steel (Fe-415)',
    vendor: 'SAIL Steel',
    category: 'steel',
    poValue: 3180000,
    gstRate: 18,
    gstAmount: 572400,
    totalValue: 3752400,
    status: 'delayed',
    expectedDelivery: '2025-06-18',
    projectId: 'KDSP-B1',
    stockLevel: 28,
    stockUnit: 'MT',
    reorderPoint: 60,
    stockoutRisk: 3,
    quantity: 150,
    quantityUnit: 'MT',
    raisedDate: '2025-06-05',
  },
  {
    id: 'PO-2853',
    item: 'HDPE Pipes (500mm dia)',
    vendor: 'Finolex Industries',
    category: 'equipment',
    poValue: 2640000,
    gstRate: 18,
    gstAmount: 475200,
    totalValue: 3115200,
    status: 'received',
    expectedDelivery: '2025-06-10',
    projectId: 'KDSP-B1',
    stockLevel: 340,
    stockUnit: 'RMT',
    reorderPoint: 200,
    stockoutRisk: 35,
    quantity: 400,
    quantityUnit: 'RMT',
    raisedDate: '2025-05-28',
    approvedBy: 'Priya Menon',
  },
  {
    id: 'PO-2854',
    item: 'Aggregates (20mm & 40mm)',
    vendor: 'Sai Quarries Pvt Ltd',
    category: 'aggregate',
    poValue: 680000,
    gstRate: 5,
    gstAmount: 34000,
    totalValue: 714000,
    status: 'received',
    expectedDelivery: '2025-06-14',
    projectId: 'NH-44X',
    stockLevel: 1840,
    stockUnit: 'CUM',
    reorderPoint: 1000,
    stockoutRisk: 28,
    quantity: 2000,
    quantityUnit: 'CUM',
    raisedDate: '2025-06-08',
    approvedBy: 'Anand Sharma',
  },
  {
    id: 'PO-2855',
    item: 'Bitumen VG-40',
    vendor: 'BPCL Bulk Division',
    category: 'fuel',
    poValue: 1560000,
    gstRate: 18,
    gstAmount: 280800,
    totalValue: 1840800,
    status: 'approved',
    expectedDelivery: '2025-07-02',
    projectId: 'NH-44X',
    stockLevel: 62,
    stockUnit: 'MT',
    reorderPoint: 80,
    stockoutRisk: 9,
    quantity: 150,
    quantityUnit: 'MT',
    raisedDate: '2025-06-18',
    approvedBy: 'Anand Sharma',
  },
  {
    id: 'PO-2856',
    item: 'Cast-In-Situ Piles Equipment Hire',
    vendor: 'Deep Foundation India',
    category: 'equipment',
    poValue: 5400000,
    gstRate: 18,
    gstAmount: 972000,
    totalValue: 6372000,
    status: 'pending',
    expectedDelivery: '2025-07-10',
    projectId: 'VIZG-P2',
    stockLevel: 0,
    stockUnit: 'LOT',
    reorderPoint: 0,
    stockoutRisk: 30,
    quantity: 1,
    quantityUnit: 'LOT',
    raisedDate: '2025-06-23',
  },
  {
    id: 'PO-2857',
    item: 'Precast Box Girders',
    vendor: 'Nagarjuna Precast',
    category: 'equipment',
    poValue: 12800000,
    gstRate: 12,
    gstAmount: 1536000,
    totalValue: 14336000,
    status: 'approved',
    expectedDelivery: '2025-08-01',
    projectId: 'BMRC-E2',
    stockLevel: 18,
    stockUnit: 'nos',
    reorderPoint: 10,
    stockoutRisk: 45,
    quantity: 80,
    quantityUnit: 'nos',
    raisedDate: '2025-06-12',
    approvedBy: 'Sunita Krishnan',
  },
  {
    id: 'PO-2858',
    item: 'Electrical Cables (HT, 11kV)',
    vendor: 'Polycab India Ltd',
    category: 'electrical',
    poValue: 2240000,
    gstRate: 18,
    gstAmount: 403200,
    totalValue: 2643200,
    status: 'received',
    expectedDelivery: '2025-06-12',
    projectId: 'BMRC-E2',
    stockLevel: 2800,
    stockUnit: 'RMT',
    reorderPoint: 1500,
    stockoutRisk: 32,
    quantity: 3000,
    quantityUnit: 'RMT',
    raisedDate: '2025-05-30',
    approvedBy: 'Sunita Krishnan',
  },
  {
    id: 'PO-2859',
    item: 'Ready Mix Concrete (M40)',
    vendor: 'UltraTech RMC',
    category: 'cement',
    poValue: 3680000,
    gstRate: 28,
    gstAmount: 1030400,
    totalValue: 4710400,
    status: 'approved',
    expectedDelivery: '2025-07-01',
    projectId: 'MUM-CST',
    stockLevel: 0,
    stockUnit: 'CUM',
    reorderPoint: 0,
    stockoutRisk: 60,
    quantity: 800,
    quantityUnit: 'CUM',
    raisedDate: '2025-06-21',
    approvedBy: 'Deepak Nambiar',
  },
  {
    id: 'PO-2860',
    item: 'Screw Piles (Marine Grade)',
    vendor: 'Atlas Copco India',
    category: 'equipment',
    poValue: 9200000,
    gstRate: 18,
    gstAmount: 1656000,
    totalValue: 10856000,
    status: 'delayed',
    expectedDelivery: '2025-06-25',
    projectId: 'VIZG-P2',
    stockLevel: 45,
    stockUnit: 'nos',
    reorderPoint: 60,
    stockoutRisk: 6,
    quantity: 120,
    quantityUnit: 'nos',
    raisedDate: '2025-06-08',
  },
  {
    id: 'PO-2861',
    item: 'Formwork (Aluminium System)',
    vendor: 'PERI India Pvt Ltd',
    category: 'formwork',
    poValue: 4100000,
    gstRate: 18,
    gstAmount: 738000,
    totalValue: 4838000,
    status: 'pending',
    expectedDelivery: '2025-07-20',
    projectId: 'HYD-M3',
    stockLevel: 0,
    stockUnit: 'SQM',
    reorderPoint: 0,
    stockoutRisk: 25,
    quantity: 2000,
    quantityUnit: 'SQM',
    raisedDate: '2025-06-24',
  },
  {
    id: 'PO-2862',
    item: 'OPC 53 Grade Cement',
    vendor: 'Ramco Cements',
    category: 'cement',
    poValue: 920000,
    gstRate: 28,
    gstAmount: 257600,
    totalValue: 1177600,
    status: 'received',
    expectedDelivery: '2025-06-16',
    projectId: 'CHN-FLY',
    stockLevel: 420,
    stockUnit: 'bags',
    reorderPoint: 200,
    stockoutRisk: 22,
    quantity: 1000,
    quantityUnit: 'bags',
    raisedDate: '2025-06-10',
    approvedBy: 'Karthik Iyer',
  },
  {
    id: 'PO-2863',
    item: 'HSD Diesel (Bulk)',
    vendor: 'IOC Bulk Division',
    category: 'fuel',
    poValue: 1480000,
    gstRate: 0,
    gstAmount: 0,
    totalValue: 1480000,
    status: 'approved',
    expectedDelivery: '2025-06-29',
    projectId: 'BMRC-E2',
    stockLevel: 12400,
    stockUnit: 'litres',
    reorderPoint: 8000,
    stockoutRisk: 14,
    quantity: 15000,
    quantityUnit: 'litres',
    raisedDate: '2025-06-22',
    approvedBy: 'Sunita Krishnan',
  },
  {
    id: 'PO-2864',
    item: 'MS Plates (10mm, IS 2062)',
    vendor: 'JSW Steel Ltd',
    category: 'steel',
    poValue: 2840000,
    gstRate: 18,
    gstAmount: 511200,
    totalValue: 3351200,
    status: 'received',
    expectedDelivery: '2025-06-17',
    projectId: 'VIZG-P2',
    stockLevel: 84,
    stockUnit: 'MT',
    reorderPoint: 50,
    stockoutRisk: 26,
    quantity: 100,
    quantityUnit: 'MT',
    raisedDate: '2025-06-05',
    approvedBy: 'Sarita Patel',
  },
  {
    id: 'PO-2865',
    item: 'Bitumen VG-30',
    vendor: 'HPCL Bulk Division',
    category: 'fuel',
    poValue: 2100000,
    gstRate: 18,
    gstAmount: 378000,
    totalValue: 2478000,
    status: 'pending',
    expectedDelivery: '2025-07-08',
    projectId: 'NH-44X',
    stockLevel: 35,
    stockUnit: 'MT',
    reorderPoint: 50,
    stockoutRisk: 8,
    quantity: 200,
    quantityUnit: 'MT',
    raisedDate: '2025-06-24',
  },
  {
    id: 'PO-2866',
    item: 'Crane Spares (Hydraulic Pump Kit)',
    vendor: 'Atlas Copco India',
    category: 'equipment',
    poValue: 480000,
    gstRate: 18,
    gstAmount: 86400,
    totalValue: 566400,
    status: 'approved',
    expectedDelivery: '2025-06-27',
    projectId: 'HYD-M3',
    stockLevel: 1,
    stockUnit: 'set',
    reorderPoint: 2,
    stockoutRisk: 2,
    quantity: 3,
    quantityUnit: 'set',
    raisedDate: '2025-06-23',
    approvedBy: 'Rajesh Nair',
  },
]

export function getPOsByProject(projectId: string): PurchaseOrder[] {
  return purchaseOrders.filter(po => po.projectId === projectId)
}

export function getProcurementSummary() {
  const totalOpen = purchaseOrders.filter(p => p.status !== 'received').reduce((s, p) => s + p.totalValue, 0)
  const delayed = purchaseOrders.filter(p => p.status === 'delayed').length
  const criticalStockout = purchaseOrders.filter(p => p.stockoutRisk <= 5).length
  const pending = purchaseOrders.filter(p => p.status === 'pending').length
  return { totalOpen, delayed, criticalStockout, pending, total: purchaseOrders.length }
}
